
Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian9"
  
  config.vm.define :nginx do |ngx|
    ngx.vm.provider :virtualbox do |vm|
      vm.name = "nginx"
      vm.memory = 1024
      vm.cpus = 2
    end
    ngx.vm.hostname = "nginx"
    ngx.vm.network :private_network, ip: "192.168.142.14"
    ngx.vm.network :forwarded_port, guest: "8080", host: "8080"
  end
  
end
