
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.synced_folder "salt/roots", "/srv/salt"
    
    config.vm.provision :salt do |salt|
        salt.masterless = true
        salt.minion_config = "salt/minion"
        salt.run_highstate = true
    end
    
    config.vm.define :influx do |influx|
        influx.vm.provider :virtualbox do |vm|
            vm.name = "influxdb"
            vm.memory = 1024
            vm.cpus = 2
        end
        influx.vm.hostname = "influxdb"
        influx.vm.network :private_network, ip: "192.168.1.12"
    end
    
    config.vm.define :tlg do |tlg|
        tlg.vm.provider :virtualbox do |vm|
            vm.name = "telegraf"
            vm.memory = 1024
            vm.cpus = 2
        end
        tlg.vm.hostname = "telegraf"
        tlg.vm.network :private_network, ip: "192.168.1.11"
    end
    
    config.vm.define :graf do |graf|
        graf.vm.provider :virtualbox do |vm|
            vm.name = "grafana"
            vm.memory = 1024
            vm.cpus = 2
        end
        graf.vm.hostname = "grafana"
        graf.vm.network :private_network, ip: "192.168.1.13"
        graf.vm.network :forwarded_port, guest: "3000", host: 8000
    end

end
