
Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian9"
  config.vm.synced_folder "/home/sumgan/workspace/proj/saltstack/", "/srv"

  config.vm.define :saltmaster do |sm|
    sm.vm.provider :virtualbox do |vm|
      vm.name = "salt-master"
      vm.cpus = 2
      vm.memory = 2048
    end
    sm.vm.hostname = "salt"
    sm.vm.provision "shell",
      inline: "apt-get -y install curl htop iftop nload dnsutils apt-transport-https python-zmq salt-common salt-minion salt-master python-pygit2"
  end
end
