
Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian9"
  config.vm.synced_folder "/home/sumgan/workspace/proj/saltstack/", "/srv"

  config.vm.define :saltmaster do |sm|
    sm.vm.provider :virtualbox do |vb|

      second_disk = 'disk2.vdi'
      unless File.exist?(second_disk)
        vb.customize ['createhd', '--filename', second_disk, '--format', 'VDI', '--size', 8192]
      end
      vb.customize ['storageattach', :id, '--storagectl', 'IDE Controller', '--port', 0, '--device', 1, '--type', 'hdd', '--medium', second_disk]

      vb.name = "salt-master"
      vb.cpus = 2
      vb.memory = 2048
    end
    sm.vm.hostname = "salt"
    sm.vm.provision "shell",
      inline: "apt-get -y install curl htop iftop nload dnsutils apt-transport-https python-zmq salt-common salt-minion salt-master python-pygit2"
  end
end
