Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.synced_folder "./srv/salt", "/srv/salt"
  
  config.vm.provision :salt do |salt|
    salt.masterless = true
    salt.minion_config = "./files/salt/minion"
    salt.run_highstate = true
  end
  
  config.vm.define :grafana do |grafana|
    grafana.vm.provider :virtualbox do |vm|
      vm.name = "grafana"
      vm.memory = 2048
      vm.cpus = 2
    end
    grafana.vm.hostname = "grafana"
    grafana.vm.network :private_network, ip: "192.168.142.14"
    grafana.vm.network :forwarded_port, guest: "3000", host: "8080"
  end

  config.vm.define :telegraf do |telegraf|
    telegraf.vm.provider :virtualbox do |vm|
      vm.name = "telegraf"
      vm.memory = 2048
      vm.cpus = 2
    end
    telegraf.vm.hostname = "telegraf"
    telegraf.vm.network :private_network, ip: "192.168.142.11"
  end
  
  config.vm.define :influxdb do |influxdb|
    influxdb.vm.provider :virtualbox do |vm|
      vm.name = "influxdb"
      vm.memory = 2048
      vm.cpus = 2
    end
    influxdb.vm.hostname = "influxdb"
    influxdb.vm.network :private_network, ip: "192.168.142.12"
  end
  
  config.vm.define :prometheus do |prometheus|
    prometheus.vm.provider :virtualbox do |vm|
      vm.name = "prometheus"
      vm.memory = 2048
      vm.cpus = 2
    end
    prometheus.vm.hostname = "prometheus"
    prometheus.vm.network :private_network, ip: "192.168.142.13"
    prometheus.vm.network :forwarded_port, guest: "9090", host: "8081"
    prometheus.vm.provision :shell, path: "./shell/prom.sh"
  end
  
end
