Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.synced_folder "src/srv/", "/srv/"

  config.vm.provider :virtualbox do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provision :init, type: "shell", path: "provisioning/script/init.sh"

  (1..1).each do |i|
    config.vm.define "minion-#{i}" do |minion|
      minion.vm.hostname = "saltminion#{i}"
      minion.vm.network :private_network, ip: "192.168.42.15#{i}", name: "vboxnet1"
      minion.vm.provision :file, source: "provisioning/config/minion.yaml", destination: "/tmp/minion"
      minion.vm.provision :install, type: "shell", path: "provisioning/script/minion.sh"
    end
  end

  config.vm.define "master" do |master|
    master.vm.hostname = "saltmaster"
    master.vm.network :private_network, ip: "192.168.42.144", name: "vboxnet1"
    master.vm.provision :file, source: "provisioning/config/master.yaml", destination: "/tmp/master"
    master.vm.provision :install, type: "shell", path: "provisioning/script/master.sh"
  end
end
