Vagrant.configure("2") do |config|

  config.vm.box_check_update = false
  config.vm.box = "debian/contrib-buster64"

  (1..3).each do |i|
    config.vm.define "dc#{i}" do |dc|
      dc.vm.hostname = "dc#{i}"
      dc.vm.network :private_network, ip: "192.168.42.12#{i}"
      dc.vm.provider :virtualbox do |vb|
        vb.cpus = 2
        vb.memory = 1024
        vb.name = "dc#{i}"
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", "70"]
      end
    end
  end

end