
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.synced_folder "salt/state", "/srv/salt"

  config.vm.define :jj do |jj|
    jj.vm.provider :virtualbox do |vm|
        vm.name = "jenkins"
        vm.memory = 1024
        vm.cpus = 2
    end
    
    jj.vm.hostname = "jenkins"
    jj.vm.network :forwarded_port, guest: "8080", host:  "8080"
    jj.vm.provision :salt do |salt|
        salt.masterless = true
        salt.minion_config = "salt/minion"
        salt.run_highstate = true
    end
  end
end
