
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    (1..3).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.hostname = "node#{i}"
            node.vm.network :private_network,
                    ip: "192.168.1.1#{i}"
            node.vm.provision "shell",
                    path: "provision.sh"
            node.vm.provider :virtualbox do |vb|
                vb.memory = 1024
                vb.cpus = 1
                vb.name = "node-#{i}"
            end
        end
    end
end
