
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  
      config.vm.provider :virtualbox do |vb|
          vb.cpus = 2
          vb.memory = 2048
      end
  
  config.vm.define :node0 do |node0|
      node0.vm.hostname = "node0"
      node0.vm.network :private_network, ip: "192.168.15.3"
  end
  
  config.vm.define :node1 do |node1|
      node1.vm.hostname = "node1"
      node1.vm.network :private_network, ip: "192.168.15.4"
  end
  
end
